### ISSUE TITLE
browser.saveFullPageScreen is not a function on wdio-image-comparison-service 2.0.0 using webdriverio 6.10.11

### ISSUE THREAD

**Issue by lajayis** [wswebcreation/wdio-image-comparison-service#53]
My wdio-image-comparison-service configuration is as follows:
[
      'image-comparison',
      {
        baselineFolder: join(
          process.cwd(),
          './visualRegressionScreenshots/reference/'
        ),
        formatImageName: '{tag}-{logName}-{width}x{height}',
        screenshotPath: join(process.cwd(), './visualRegressionScreenshots/'),
        savePerInstance: true,
        autoSaveBaseline: true,
        blockOutStatusBar: true,
        blockOutToolBar: true,
        misMatchTolerance: 6.5,
      },
    ],
The function was working on the previous version (webdriverio 5) however, after upgrading to webdriverio 6.10.12 coupled with the use of node version 12+, I started getting browser.saveFullPageScreen is not a function. Could someone please help with this issue?

**Comment by wswebcreation** [comment]
Can you please provide your full config? Otherwise we can't debug.

Root cause of this issue is most of the time that the service is overwritten because it's mentioned twice in the config

**Comment by lajayis** [comment]
Many thanks @wswebcreation. What I am not sure of is the fact that I did not change any of the previous configuration settings before and after the upgrade from webdriverio 5 to 6 and it was working perfectly before the upgrade. Below is the full config:

const baseConfig = {

  services: [
    ['selenium-standalone'],
    ['multiple-cucumber-html'],

    [
      'image-comparison',
      {
        baselineFolder: join(
          process.cwd(),
          './visualRegressionScreenshots/reference/'
        ),
        formatImageName: '{tag}-{logName}-{width}x{height}',
        screenshotPath: join(process.cwd(), './visualRegressionScreenshots/'),
        savePerInstance: true,
        autoSaveBaseline: true,
        blockOutStatusBar: true,
        blockOutToolBar: true,
        misMatchTolerance: 6.5,
      },
    ],
  ],

  environment,
  baseUrl: appUrls.url,
  logLevel: environment.logLevel,
  sync: true,
  coloredLogs: true,
  specs: [`./${environment.features}`],
  exclude: [],
  waitforTimeout: 30000,
  waitforInterval: 200,
  connectionRetryTimeout: 30000,
  connectionRetryCount: 5,
  framework: 'cucumber',
  reporters: [
    'dot',
    'spec',
    'cucumberjs-json',
    [
      'cucumberjs-json',
      {
        jsonFolder: './report/cucumber/',
        language: 'en',
      },
    ],
  ],

  plugins: {
    'wdio-screenshot': {},
  },
  cucumberOpts: {
    compiler: ['js:@babel/register'],
    require: [path.resolve(__dirname, '../step_definitions/**/*.js')],
    backtrace: true,
    dryRun: false,
    failFast: false,
    format: ['pretty'],
    colors: true,
    snippets: true,
    source: true,
    profile: [],
    strict: false,
    tagExpression,
    timeout: 600000,
    ignoreUndefinedDefinitions: false,
  },
  ...hooks,
};

export default deepmerge(baseConfig, executorConfig);

**Comment by wswebcreation** [comment]
@lajayis 

Thanks for the config, but this looks like it's not all. Can you also provide the rest, with rest I mean the `executorConfig`
Secondly, can you also print the `browser` before you execute the `saveFullPageScreen ` command and put that in here?

**Comment by lajayis** [comment]
@wswebcreation Thanks for your response, while I may not be able to print the screen here, any web page can be used for this. The config file including the executorConfig is as follows:

const executorConfig =
  environment.executor === 'seleniumStandalone'
    ? seleniumStandaloneConfig
    : seleniumGridConfig;

const baseConfig = {

  services: [
    ['selenium-standalone'],
    ['multiple-cucumber-html'],

    [
      'image-comparison',
      {
        baselineFolder: join(
          process.cwd(),
          './visualRegressionScreenshots/reference/'
        ),
        formatImageName: '{tag}-{logName}-{width}x{height}',
        screenshotPath: join(process.cwd(), './visualRegressionScreenshots/'),
        savePerInstance: true,
        autoSaveBaseline: true,
        blockOutStatusBar: true,
        blockOutToolBar: true,
        misMatchTolerance: 6.5,
      },
    ],
  ],

  environment,
  baseUrl: appUrls.url,
  logLevel: environment.logLevel,
  sync: true,
  coloredLogs: true,
  specs: [`./${environment.features}`],
  exclude: [],
  waitforTimeout: 30000,
  waitforInterval: 200,
  connectionRetryTimeout: 30000,
  connectionRetryCount: 5,
  framework: 'cucumber',
  reporters: [
    'dot',
    'spec',
    'cucumberjs-json',
    [
      'cucumberjs-json',
      {
        jsonFolder: './report/cucumber/',
        language: 'en',
      },
    ],
  ],

  plugins: {
    'wdio-screenshot': {},
  },
  cucumberOpts: {
    compiler: ['js:@babel/register'],
    require: [path.resolve(__dirname, '../step_definitions/**/*.js')],
    backtrace: true,
    dryRun: false,
    failFast: false,
    format: ['pretty'],
    colors: true,
    snippets: true,
    source: true,
    profile: [],
    strict: false,
    tagExpression,
    timeout: 600000,
    ignoreUndefinedDefinitions: false,
  },
  ...hooks,
};

export default deepmerge(baseConfig, executorConfig);

Here is the function to print the full page:

class VisualRegressionUtils {

  **checkVisualRegressionOfPage** = () => {
    const pageTitle = browser.getTitle();
    expect(browser.checkFullPageScreen('fullPage', { /* some options */ })).toEqual(0);
  }
}
export default new VisualRegressionUtils();

**Comment by wswebcreation** [comment]
Hi @lajayis 

Thanks, what I mean with the logging the browser is if you can do `console.log(browser)`, that would print the browser including the config to the console and then we can see if the service was added correctly

What you can also do is add `logLevel:'debug'`, and past the logs of the start of the session here (not the complete session, I'm curious what the hooks will log)

**Comment by lajayis** [comment]
Hi @wswebcreation I am not sure if this will be helpful, below are the console logs (with some irrelevant part removed):

TypeError: browser.checkFullPageScreen is not a function
    at VisualRegressionUtils.checkVisualRegressionOfPage (/Users/xxxxxxxxx/support/VisualRegressionTestUtils.js:9:31)
    at World.<anonymous> (/Users/xxxxxxxxxxxxxxxxxxx/visualRegressionSteps.js:52:32)
[0-0] FAILED in chrome - /features/web/xxx.feature

[Chrome 87.0.4280.141 darwin #0-0] browser.checkFullPageScreen is not a function
[Chrome 87.0.4280.141 darwin #0-0] TypeError: browser.checkFullPageScreen is not a function
[Chrome 87.0.4280.141 darwin #0-0]     at VisualRegressionUtils.checkVisualRegressionOfPage (/Users/xxxxxxxxxx/support/VisualRegressionTestUtils.js:9:31)
[Chrome 87.0.4280.141 darwin #0-0]     at World.<anonymous> (/Users/xxxxxxx/step_definitions/web/xxxxxx/visualRegressionSteps.js:52:32)

**Comment by wswebcreation** [comment]
Hi @lajayis 

There should be more, the debug logs should provide more logs about starting the process, I would like to have the first few lines where the services are initiated, can you provide that?

**Comment by lajayis** [comment]
@wswebcreation I am not sure of what you are referring to as the starting process, at the moment all other tests are passing, the only one that is not passing is the visual regression test which is due to the problem with "browser.checkFullPageScreen is not a function". If what you are referring to is the selenium service, it is working fine. The following log is the beginning of the test:

Webdriver.io started

- BaseUrl : https://xxxxxxxxx/login
Environment:
- build          : "xxxxxxxxx"
- executor       : "seleniumStandalone"
- logLevel       : "silent"
- infrastracture : "xxxxx"
- deployment     : "xxx"
- brand          : "xxx"
- features       : "xxxxxxx.feature"
- seleniumGrid   : {"protocol":"http","host":"selenium-xxxxx.zone","port":xxxxx,"instances":20}
--------------------------------------
[0-0] Inside GetBluemix urlhttps://xxxxxxxxxxxx/login
[0-0] RUNNING in chrome - /features/xxxxxxxxx.feature
[0-0] Base Page

**Comment by wswebcreation** [comment]
Hi @lajayis 

Sorry for my late response, what I mean with it is this. When you run your command with `logLevel=debug` you will get extra logs as below. In the first line you will see all the hooks being started, in my case you see the `WdioImageComparisonService` and `selenium-standalone` being started. 
I wonder how your log looks like. 

```log
yarn test.local.desktop --logLevel=debug                              
yarn run v1.22.10
$ wdio tests/configs/wdio.local.desktop.conf.js --logLevel=debug
2021-01-23T08:00:45.858Z DEBUG @wdio/config:utils: Couldn't find ts-node package, no TypeScript compiling

Execution of 4 spec files started at 2021-01-23T08:00:45.922Z

2021-01-23T08:00:45.923Z DEBUG @wdio/utils:initialiseServices: initialise custom service "WdioImageComparisonService"
2021-01-23T08:00:45.923Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
2021-01-23T08:00:45.984Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-01-23T08:00:50.242Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 4258ms
2021-01-23T08:00:50.246Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-01-23T08:00:50.246Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-01-23T08:00:50.246Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-01-23T08:00:50.246Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-01-23T08:00:50.246Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2021-01-23T08:00:50.246Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2021-01-23T08:00:50.246Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2021-01-23T08:00:50.247Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 1ms
2021-01-23T08:00:50.247Z INFO @wdio/local-runner: Start worker 0-0 with arg: tests/configs/wdio.local.desktop.conf.js,--logLevel=debug
2021-01-23T08:00:50.253Z INFO @wdio/local-runner: Start worker 0-1 with arg: tests/configs/wdio.local.desktop.conf.js,--logLevel=debug
2021-01-23T08:00:50.256Z INFO @wdio/local-runner: Start worker 0-2 with arg: tests/configs/wdio.local.desktop.conf.js,--logLevel=debug
2021-01-23T08:00:50.259Z INFO @wdio/local-runner: Start worker 0-3 with arg: tests/configs/wdio.local.desktop.conf.js,--logLevel=debug
```

**Comment by Elichkoto** [comment]
Hi there,

I have exactly the same problem.
My wdio-cli is version **6.10.11**

I logged the browser object:
`Browser {
  sessionId: '1776e165-07fc-4954-984d-052fd0dd237b',
  capabilities: {
    browserName: 'Chrome',
    browserVersion: '88.0.4324.190',
    platformName: 'win32',
    platformVersion: '10.0.18363'
  },
  addCommand: [Function (anonymous)],
  overwriteCommand: [Function (anonymous)],
  addLocatorStrategy: [Function (anonymous)],
  config: {
    hostname: undefined,
    port: undefined,
    protocol: undefined,
    path: undefined,
    specs: [ './build/src/__e2e__/features/**/*.feature' ],
    suites: {},
    exclude: [],
    outputDir: 'C:\\UI automation\\new project\\ShapeAutomatedTests\\shape-typescript-fta\\build\\logs',
    logLevel: 'debug',
    logLevels: {},
    excludeDriverLogs: [],
    bail: 0,
    waitforInterval: 500,
    waitforTimeout: 1000000,
    framework: 'cucumber',
    reporters: [ 'spec' ],
    services: [ [Array] ],
    maxInstances: 10,
    maxInstancesPerCapability: 100,
    filesToWatch: [],
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    execArgv: [],
    runnerEnv: {},
    runner: 'local',
    mochaOpts: { timeout: 10000 },
    jasmineNodeOpts: { defaultTimeoutInterval: 10000 },
    cucumberOpts: {
      timeout: 10000,
      backtrace: false,
      requireModule: [Array],
      failAmbiguousDefinitions: true,
      failFast: false,
      ignoreUndefinedDefinitions: false,
      name: [],
      snippets: true,
      source: true,
      profile: [],
      require: [Array],
      snippetSyntax: undefined,
      strict: true,
      tagExpression: 'not @Pending',
      tagsInTitle: false
    },
    onPrepare: [],
    onWorkerStart: [],
    before: [],
    beforeSession: [],
    beforeSuite: [],
    beforeHook: [],
    beforeTest: [],
    beforeCommand: [],
    afterCommand: [],
    afterTest: [],
    afterHook: [],
    afterSuite: [],
    afterSession: [],
    after: [],
    onComplete: [],
    onReload: [],
    beforeFeature: [],
    beforeScenario: [],
    beforeStep: [],
    afterStep: [],
    afterScenario: [],
    afterFeature: [],
    baseUrl: 'http://localhost:8080',
    _: [ './build/wdio.conf.js' ],
    '$0': 'node_modules\\@wdio\\cli\\bin\\wdio.js',
    ignoredWorkerServices: [],
    specFileRetryAttempts: 0
  }
}`

Here's the logs of the debug mode:
`2021-02-25T19:32:02.976Z DEBUG @wdio/utils:initialiseServices: initialise service "image-comparison" as NPM package
2021-02-25T19:32:03.021Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-image-comparison-service".
Error: Cannot find module '../build/Release/canvas.node'`

Do you want me to provide the call stack?

Hope it helps.

**Comment by wswebcreation** [comment]
hi @Elichkoto 

Thanks for the info. It looks like the service was initialised, see you logs, but the canvas module was not installed. Which version of Node are you on? Did you also got some issues while installing all modules?

**Comment by Elichkoto** [comment]
I'm using version 15.0.1.

And yes, I was having trouble installing it, but I deleted my package-lock.json and it worked out.

**Comment by wswebcreation** [comment]
@Elichkoto 

As far as I understood NodeJs 15 is not yet supported by `canvas` which might cause this issue. Are you able to check it on NodeJS14?

**Comment by Elichkoto** [comment]
Hi there,

I'm facing the following issue:
`bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" rebuild --release )
internal/modules/cjs/loader.js:883
  throw err;

Error: Cannot find module 'C:\usr\local\lib\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

**Comment by Elichkoto** [comment]
Hey, @wswebcreation ,

Any suggestions on that? :)

Regards,
Ellie

**Comment by wswebcreation** [comment]
Hi @Elichkoto 

Are you using NodeJS 14 already of are you still on 15? This error means that Canvas doesn't have the prebuild version for you and it will try to build it from source, but therefore you need to have `node-gyp` installed.
Have you already tried that?
